# Generated by Django 4.0.2 on 2022-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('username_id', 'name')},
        ),
    ]
